### ISSUE TITLE
babel(?) issue

### ISSUE THREAD

**Issue by PawelDmochowski** [valterlorran/vuejs-localization#1]
In index.js, lines 67 and 76 ES6 syntax is used that is not translated by babel to ES5 (in standard laravel-mix setup).

**Comment by valterlorran** [comment]
Hello! I fixed it: 
https://github.com/valterlorran/vuejs-localization/commit/bdb61fb3846e427e17821bfc51143f67dda7c870

**Comment by PawelDmochowskiDRAST** [comment]
Installing updated version with NPM ignores this last commit.
