### ISSUE TITLE
Put bold tag inside language var

### ISSUE THREAD

**Issue by ArnaudCartailler** [valterlorran/vuejs-localization#15]
Hi,
I'm using this package and I have a question.
I write some long sentences, and I need to bold some words.
I can't cut all the sentence just to recover only a few words to bold them. 
Is there any issue to use bold tag or something else inside the js file who contains lang var ? 

Thanks for your attention.

Arnaud Cartailler

**Comment by valterlorran** [comment]
Hi Arnaud,
You could set the message like: 'Some <strong>message</strong>' and use the v-html to print the text.
Sorry for taking so long to answer.
