### ISSUE TITLE
Messages are not refreshed in components

### ISSUE THREAD

**Issue by mirontoli** [valterlorran/vuejs-localization#3]
Hi, we use vuejs-localization in [our project](https://github.com/sunafajro/samahsar/). It works fine in the main Vue instance - the messages are refreshed when we change the language in the UI. But it does not refresh labels in the components. It does, though work fine when we refresh the page and the last language is set from cookies.

Kind regards,
Anatoly

**Comment by valterlorran** [comment]
Hi @mirontoli I'll take a look right now!

**Comment by sunafajro** [comment]
Branch "i18n". We use "this.$lang.setLang('ru')" in main.js and the messages in the "&lt;App&gt;" block are changing successfully. But messages that are output to the "&lt;router-view&gt;&lt;/router-view&gt;" block remain unchanged. I tried to track the state of the $lang (watch: '$lang') in the Home.vue component, but unsuccessfully.
