### ISSUE TITLE
Package not updated in NPM

### ISSUE THREAD

**Issue by tpalts** [valterlorran/vuejs-localization#6]
in this projecf, index.js was last updated 7m ago, package.json was last updated a year ago. downloading the latest version from npm does not fetch the latest update to index.js.

**Comment by adrianjost** [comment]
@valterlorran could you update the package on npm please? It's annoying that everyone in our team needs to update their package manually by downloading it from github. It's such a cool package. I think more people would use it if there woudn't be this issue.
Thanks

**Comment by valterlorran** [comment]
@adrianjost I just updated man. Thank you
